### ISSUE TITLE
Not Open Source!

### ISSUE THREAD

**Issue by Zormein** [Faithful-Resource-Pack/Branding#5]
Hey,

I would like to report a lie by you guys! So you guys say that: 
"All of our work is free and **open source**, we don't use any money
making download links and don't do any ads or data collection. "

When in reality the definition of open source has this in it: 
"1. Free Redistribution: **The license shall not restrict any party from selling or giving away the software** as a component of an aggregate software distribution containing programs from several different sources. The license shall not require a royalty or other fee for such sale."

And your license says this:
"4. **Do not monetise** under any circumstances"

So this shows that your branding is lying!

Sources: 
https://github.com/Faithful-Resource-Pack
https://opensource.org/osd
https://faithfulpack.net/license

**Comment by RobertRR11** [comment]
All of our work meant the code that we publish, which is open source. The Resource Packs themselves are free but not open source due to the textures being made by a community of artists from which we do not have the permissions of making all the textures fully "open source".
I have now changed the description to specifically say that our code is open source.
